spring:
 # profiles不同环境配置标识，如开发、测试、生产环境等
  profiles: development
  # 应用名称，自定义
  application:
    name: platform
  messages:
    basename: i18n/messages-common
  # 如果要访问WEB-INF下的视图文件开启如下配置
  # 这里不配置suffix方便混合使用不同视图如同时使用jsp、html都可以，在Controller返回视图时带上后缀即可
  # 特别的如果要访问WEB-INF下的html文件，必须配置com.jackie0.common.config.MvcConfiguration，jsp则不用
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix:
---
spring:
  profiles: test
db:
  url: jdbc:mysql://localhost/test
  username: test
  password: test